[build]
  publish = "dist"
  command = "npm run build"
  

[functions]
  directory = "netlify/functions"
  # node_bundler = "esbuild"  # optional; defaults to esbuild

# Note: schedule is defined inside code via `schedule('*/5 * * * *', handler)`

